# Generated by Django 4.2.30 on 2026-05-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_score', models.IntegerField(verbose_name='维修速度评分')),
                ('attitude_score', models.IntegerField(verbose_name='服务态度评分')),
                ('quality_score', models.IntegerField(verbose_name='维修质量评分')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='文字评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='repairs.workorder', verbose_name='对应工单')),
            ],
            options={
                'verbose_name': '服务评价',
                'verbose_name_plural': '服务评价',
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quality', '维修质量'), ('attitude', '服务态度'), ('other', '其他')], default='quality', max_length=20, verbose_name='投诉类型')),
                ('content', models.TextField(max_length=1000, verbose_name='投诉内容')),
                ('process_result', models.TextField(blank=True, max_length=1000, null=True, verbose_name='处理结果')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已处理')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投诉人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='repairs.workorder', verbose_name='对应工单')),
            ],
            options={
                'verbose_name': '投诉记录',
                'verbose_name_plural': '投诉记录',
                'db_table': 'complaint',
            },
        ),
    ]
