# Generated by Django 4.2.30 on 2026-05-25 11:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(max_length=20, unique=True, verbose_name='楼栋编号')),
                ('building_name', models.CharField(max_length=50, verbose_name='楼栋名称')),
                ('gender_limit', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别限制')),
            ],
            options={
                'verbose_name': '宿舍楼',
                'verbose_name_plural': '宿舍楼',
                'db_table': 'dorm_building',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_or_staff_no', models.CharField(db_index=True, max_length=30, verbose_name='学号/工号')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('role', models.CharField(choices=[('student', '学生'), ('admin', '宿舍管理员'), ('maintainer', '维修人员')], max_length=20, verbose_name='角色')),
                ('status', models.SmallIntegerField(default=1, verbose_name='账号状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DormRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(db_index=True, max_length=20, verbose_name='房间号')),
                ('floor_no', models.IntegerField(verbose_name='楼层')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.dormbuilding', verbose_name='所属楼栋')),
            ],
            options={
                'verbose_name': '宿舍房间',
                'verbose_name_plural': '宿舍房间',
                'db_table': 'dorm_room',
                'unique_together': {('building', 'room_no')},
            },
        ),
    ]
